#!/bin/zsh

function switch() {
	case "$1" in
		# switch system
		system)
		shift
		nh os switch "$@"
		;;
		# switch user
		user)
		shift
		nh home switch "$@"
		;;
		# switch
		*) 
		nh os switch "$@" || {
			return 1
		}

	nh home switch "$@"
	;;
esac
}

function _switch() {
	local -a subcmds
	subcmds=(
		'system:Build and activate a new NixOS configuration, and make it the boot default'
		'user:Build and activate a new Home-manager configuration'
	)

	_describe 'command' subcmds
}

compdef _switch switch

shell() {
  nix develop --impure ".#$1" --command "zsh" 2> /dev/null || {
		nix shell --impure "${(@)argv/#/nixpkgs#}" --command "zsh"
  }
}

run() {
  local pkg=$1

  if [ -n "$1" ]; then
    shift
  fi

  nix run --impure ".#$pkg" -- "$@" 2> /dev/null || {
    nix run --impure "nixpkgs#$pkg" -- "$@"
  }
}

bindkey "^H" backward-kill-word
bindkey "5~" kill-word
